### ISSUE TITLE
Links broken

### ISSUE THREAD

**Issue by LuisFranciscoHS** [bjornwallner/ML_medbioinfo#2]
Hei,

On the file https://github.com/bjornwallner/ML_medbioinfo/blob/master/README.md
Section 4, the following links say page not found:
https://github.com/bjornwallner/ML_medbioinfo/blob/master/data/ProQdock.csv
http://archive.ics.uci.edu/ml/datasets.html

**Comment by bjornwallner** [comment]
Thanks links updated.

cheers
Björn Wallner
Associate Professor
Head of Bioinformatics Division

[cid:9D0BA4B3-449A-4A09-9130-42D30C9F7590]

Department of Physics, Chemistry and Biology
581 83 Linköping
Telephone: 013-28 27 59
Mobile: 070-521 56 65
Visiting address: 2B:580 (B-huset)





On 4 May 2019, at 22:15, Luis Francisco Hernández Sánchez <notifications@github.com<mailto:notifications@github.com>> wrote:


Hei,

On the file https://github.com/bjornwallner/ML_medbioinfo/blob/master/README.md
Section 4, the following links say page not found:
https://github.com/bjornwallner/ML_medbioinfo/blob/master/data/ProQdock.csv
http://archive.ics.uci.edu/ml/datasets.html

**Comment by LuisFranciscoHS** [comment]
Thanks!
